Structure: Ducks 

Models:

  - dux:

    Slice:
      - Name: string
      - Quacking: Boolean
      - Ducklings: Object
      - Fly2Gether: Boolean

    Actions:
      - countDux


    Thunks:
      - getAll:
        - "/api/Dux" 
        - countDux
      - getSome:
        - "/api/Dux" 
        - countDux
     
  - Ducklings:

    Slice:
      - Name: string
    
    Actions:
      - countDucklings 
        