Structure: Rails 

Models:

  - dux:

    Slice:
      - Name: string
      - Quacking: Boolean
      - Ducklings: Object
      - Fly2Gether: Boolean

    Actions:
      - countDux
      - migrateDux
      - quackOne

    Thunks:
      - getAll:
        - "/api/Dux" 
        - countDux
      - getOne: 
        - "/api/Dux/:dux"
        - migrateDux

  - Ducklings:

    Slice:
      - Name: string
    
    CRUD: false

    Actions:
      - countDucklings
      - migrateDucklings
      - quackOne

    Thunks:
      - getAll:
        - "/api/Dux" 
        - countDucklings
      - getOne: 
        - "/api/Dux/:dux"
        - migrateDucklings
        