#prettier-ignore
Structure: Ducks

Models:
  - campus:

    Slice:
      - Name: string
      - Quacking: Boolean
      - Ducklings: Object
      - Fly2Gether: Boolean

    CRUD: true;

    Actions:
      - countDux
      - migrateDux
      - quackOne

    Thunks:
      - getAll:
          - "/api/Dux"
          - getAllCampus
      - getOne:
          - "/api/Dux/${payload}"
          - getCampus
