# { model: 'Duck Chicken' } 'rails'

File_Structure: Rails

Models:
  - Campus:
      - Name: string
      - Address: Boolean
      - Phone Number: Array

  - Student:
      - First Name: Number
      - Last Name: Boolean
      - Campus: Array
      - GPA: Number
