Structure: Ducks

Models:

  - Ducks:

    Slice:
      - Name: string
      - Quacking: Boolean
      - Ducklings: Object
      - Fly2Gether: Boolean

  - Terminator:

    Slice:
      - Name: string
      - isBack: Boolean
      - timeTravel: Object
      - JohnConnorGot: Boolean

      