
# This is a sample of a lamp.config.yml configuration.
# Please visit https://redux-genie.herokuapp.com/ for a guided tutorial for creating your own YML configuration file.

Structure: Ducks # Ducks || Rails

Models:
  - trains:

    Slice:
      - color: string
      - cars: number
      - inTransit: boolean
      - conductors: array
      - stations: object

    Thunks:
      - sendToStationThunk:
          - /api/stations
          - sendToStation

  - ducks:

    Slice:
      - feathers: string
      - flockSize: number
      - isMigrating: boolean
      - sightings: array
      - flockMembers: object

    CRUD: false

    Actions:
      - flyTogether
      - seasonState

    Thunks:
      - migrateSouthThunk:
          - /api/geese
          - goSouth
