Structure: Ducks # Two options: Rails || Ducks

# Thunks: included # thunks will be included in the same file as the actions
# Logging: false  # configures logging middleware

Models:

  - dux:

    Slice:
      - Name: string
      - Quacking: Boolean
      - Ducklings: Object
      - Fly2Gether: Boolean

    # CRUD: false

    # Actions:
    #   - countDux
    #   - migrateDux
    #   - quackOne

    # Thunks:
    #   - getAll: "/api/Dux"
    #   - getOne: "/api/Dux/:dux"
    #   - getStuff: "/api/Dux/getStuff"

  - terminator:

    Slice:
      - WillBeBack: Boolean
      - OneLiners: Array
      - Sequels: Number

    # Actions:
    #   - killJohnConnor
    #   - backInTime

    # Thunks:
    #   - getAll: "api/terminator"
    #   - getOne: "api/terminator/:terminator"

  # - Ducklings: 

  #   Slice: 
  #     - lilFeet: Array
