# { model: 'Duck Chicken' } 'rails'

File_Structure: Rails

Models:
  - Dux: 
    - Name : string
    - Quacking : Boolean
    - Ducklings: Array
  - Terminator:
    - Kills: Number
    - WillBeBack: Boolean
    - OneLiners: Array
    - Sequels: Number
