Structure: ducks  # Available options: Rails || Ducks  

# Thunks: separated # thunks will be written in a seaprate file from actions
# Logging: true  # configures logging middleware

Models:
  - Dux: 
    - Name : string 
    - Quacking : Boolean (false) 
    - Ducklings: Object 
    - Fly2Gether: Boolean (true)
    # - Thunks: 
    #   - getAll: '/api/Dux' 
    #   - getOne: '/api/Dux/:dux' 
  - Terminator: 
    - WillBeBack: Boolean (true)
    - OneLiners: Array 
    - Sequels: Number 
    # - Thunks:
    #   - getAll: 'api/terminator'
    #   - getOne: 'api/terminator/:terminator'

# Normalize: 
#   Associate: 


